services:
  # vector open source database, run condole on localhost:6333/dashboard
  qdrant:
    image: 'qdrant/qdrant:v1.13.0'
    ports:
      - '6333:6333'
      - '6334:6334'
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - spring-ai
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - spring-ai

networks:
  spring-ai:
    driver: bridge

volumes:
  grafana-storage: